// src/renderer/src/components/CommitDetails.tsx
import { ChevronDown, ChevronRight, GitCommit, GitFork, Hash, RotateCcw, UserRound } from 'lucide-react'
import { useEffect, useState } from 'react'
import type { CommitDetails as CommitDetailsData, CommitNode, DiffLine } from '@shared/types'

interface Props {
  commit: CommitNode
  refresh: () => Promise<unknown>
  notify: (message: string) => void
}

const STATUS_COLOR: Record<string, string> = { A: 'b-a', M: 'b-m', D: 'b-d', U: 'b-u' }

export default function CommitDetails({ commit, refresh, notify }: Props) {
  const [details, setDetails] = useState<CommitDetailsData | null>(null)
  const [openFile, setOpenFile] = useState<string | null>(null)
  const [fileDiff, setFileDiff] = useState<DiffLine[]>([])
  const [showFiles, setShowFiles] = useState(true)

  useEffect(() => {
    let cancelled = false
    setDetails(null)
    setOpenFile(null)
    window.api.commitDetails(commit.hash).then((value) => {
      if (!cancelled) setDetails(value)
    }).catch((error) => notify(String(error).replace(/^Error:\s*/, '')))
    return () => { cancelled = true }
  }, [commit.hash, notify])

  useEffect(() => {
    if (!openFile) return
    let cancelled = false
    window.api.commitFileDiff(commit.hash, openFile).then((diff) => {
      if (!cancelled) setFileDiff(diff)
    }).catch(() => setFileDiff([]))
    return () => { cancelled = true }
  }, [commit.hash, openFile])

  const action = async (label: string, fn: () => Promise<unknown>) => {
    try {
      await fn()
      await refresh()
      notify(label)
    } catch (error) {
      notify(String(error).replace(/^Error:\s*/, ''))
    }
  }

  const message = details?.message || commit.subject
  const summary = message.split('\n')[0]
  const body = message.split('\n').slice(2).join('\n').trim()

  return (
    <section className="commit-details">
      <div className="commit-details-heading">
        <div className="commit-details-title"><GitCommit size={16} /><strong>Commit details</strong></div>
        <span className="commit-details-hash"><Hash size={13} />{commit.shortHash}</span>
      </div>
      <div className="commit-details-content">
        <div className="commit-details-summary">{summary}</div>
        {body && <div className="commit-details-body">{body}</div>}
        <div className="commit-meta">
          <span><UserRound size={14} />{details?.author || commit.author}</span>
          <span>{formatDate(details?.date || commit.date)}</span>
          <button className="detail-action" onClick={() => setShowFiles((value) => !value)}>
            {showFiles ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
            {details ? `${details.files.length} changed files` : 'Loading…'}
          </button>
          <span className="spacer" />
          <button className="detail-action" title="Checkout this commit" onClick={() => void action('Checked out commit (detached HEAD)', () => window.api.checkoutCommit(commit.hash))}>Checkout</button>
          <button className="detail-action" title="Cherry-pick onto current branch" onClick={() => void action('Cherry-picked', () => window.api.cherryPick(commit.hash))}>Cherry-pick</button>
          <button className="detail-action danger" title="Revert this commit" onClick={() => {
            if (window.confirm(`Revert commit ${commit.shortHash}?`)) void action('Commit reverted', () => window.api.revertCommit(commit.hash))
          }}><RotateCcw size={12} /> Revert</button>
        </div>
        <div className="commit-ref-list">
          {commit.refs.map((ref) => <span key={ref} className="ref-chip">{ref}</span>)}
          {commit.parents.length > 0 && <span className="parent-meta"><GitFork size={13} /> Parent {commit.parents[0].slice(0, 7)}</span>}
        </div>

        {showFiles && details && details.files.length > 0 && (
          <div className="commit-files">
            {details.files.map((file) => (
              <div key={file.path}>
                <div
                  className={`commit-file-row${openFile === file.path ? ' selected' : ''}`}
                  onClick={() => setOpenFile(openFile === file.path ? null : file.path)}
                >
                  <span className={`badge ${STATUS_COLOR[file.status.toUpperCase()] ?? 'b-m'}`}>{file.status}</span>
                  <span className="commit-file-path" title={file.path}>{file.path}</span>
                </div>
                {openFile === file.path && (
                  <div className="commit-file-diff">
                    {fileDiff.map((line, index) => (
                      <div key={index} className={`diff-line ${line.type}`}>
                        <span className="ln">{line.oldNo ?? ''}</span>
                        <span className="ln">{line.newNo ?? ''}</span>
                        <pre>{line.text}</pre>
                      </div>
                    ))}
                    {fileDiff.length === 0 && <div className="diff-empty">No textual diff available</div>}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  )
}

function formatDate(value: string): string {
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return date.toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })
}

// src/renderer/src/components/CommitDetails.vue
<script setup lang="ts">
    import { GitCommitHorizontal, RotateCcw } from 'lucide-vue-next'

    import type { CommitDetails as CommitDetailsData, CommitNode } from '@shared/types'

    const props = defineProps<{ commit: CommitNode; notify: (message: string) => void }>()
    const refresh = inject<() => Promise<unknown>>('refresh', async () => {})

    const details = ref<CommitDetailsData | null>(null)

    watch(
        () => props.commit.hash,
        async () => {
            details.value = null
            try {
                details.value = await window.api.commitDetails(props.commit.hash)
            } catch (error) {
                useUiStore().notify(String(error).replace(/^Error:\s*/, ''))
            }
        },
        { immediate: true }
    )

    function checkoutCommit() {
        void run('Checked out commit (detached HEAD)', () => window.api.checkoutCommit(props.commit.hash))
    }
    function cherryPick() {
        void run('Cherry-picked', () => window.api.cherryPick(props.commit.hash))
    }
    function checkoutNow() {
        void run('Checked out commit (detached HEAD)', () => window.api.checkoutCommit(props.commit.hash))
    }
    function cherryPickNow() {
        void run('Cherry-picked', () => window.api.cherryPick(props.commit.hash))
    }
    function revertCommit() {
        if (!window.confirm(`Revert commit ${props.commit.shortHash}?`)) return
        void run('Commit reverted', () => window.api.revertCommit(props.commit.hash))
    }

    async function run(label: string, fn: () => Promise<unknown>) {
        try {
            await fn()
            await refresh()
            props.notify(label)
        } catch (error) {
            useUiStore().notify(String(error).replace(/^Error:\s*/, ''))
        }
    }

    const message = computed(() => details.value?.message || props.commit.subject)
    const summary = computed(() => message.value.split('\n')[0])
    const body = computed(() => message.value.split('\n').slice(2).join('\n').trim())

    function formatDate(value: string): string {
        const date = new Date(value)
        if (Number.isNaN(date.getTime())) return value
        return date.toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })
    }
</script>

<template>
    <section class="commit-details">
        <div class="commit-details-heading">
            <div class="commit-details-title">
                <GitCommitHorizontal :size="16" />
                <strong>Commit details</strong>
            </div>
            <span class="commit-details-hash">{{ commit.shortHash }}</span>
        </div>
        <div class="commit-details-content">
            <div class="commit-details-summary">{{ summary }}</div>
            <div
                v-if="body"
                class="commit-details-body">
                {{ body }}
            </div>
            <div class="commit-meta">
                <span>{{ details?.author || commit.author }}</span>
                <span>{{ formatDate(details?.date || commit.date) }}</span>
                <span>{{ details ? `${details.files.length} changed files` : 'Loading…' }}</span>
            </div>
            <div class="commit-ref-list">
                <span
                    v-for="ref in commit.refs"
                    :key="ref"
                    class="ref-chip"
                    >{{ ref }}</span
                >
                <span
                    v-if="commit.parents.length"
                    class="parent-meta">
                    Parent {{ commit.parents[0].slice(0, 7) }}
                </span>
                <span class="commit-detail-actions">
                    <button
                        class="detail-action"
                        title="Checkout this commit"
                        @click="checkoutCommit()">
                        Checkout
                    </button>
                    <button
                        class="detail-action"
                        title="Cherry-pick onto current branch"
                        @click="cherryPick()">
                        Cherry-pick
                    </button>
                    <button
                        class="detail-action danger"
                        title="Revert this commit"
                        @click="revertCommit()">
                        <RotateCcw :size="12" /> Revert
                    </button>
                </span>
            </div>
        </div>
    </section>
</template>
