// src/renderer/src/components/ConflictBanner.vue
<script setup lang="ts">
    import { AlertTriangle, ArrowLeftRight, Check, X } from 'lucide-vue-next'

    import type { RepoState } from '@shared/types'

    const props = defineProps<{
        conflicts: string[]
        state: RepoState
        refresh: () => Promise<unknown>
    }>()
    const notify = inject<(m: string) => void>('notify', () => {})

    function abortMerge() {
        void run(() => window.api.abortMerge(), 'Merge aborted')
    }
    function continueMerge() {
        void run(() => window.api.continueMerge(), 'Merge completed')
    }
    function abortRebase() {
        void run(() => window.api.rebaseAbort(), 'Rebase aborted')
    }
    function continueRebase() {
        void run(() => window.api.rebaseContinue(), 'Rebase continued')
    }
    function takeOurs(file: string) {
        void run(() => window.api.conflictTakeSide(file, 'ours'), `${file}: kept ours`)
    }
    function markResolved(file: string) {
        void run(() => window.api.markResolved([file]), `${file}: resolved`)
    }
    function takeTheirs(file: string) {
        void run(() => window.api.conflictTakeSide(file, 'theirs'), `${file}: kept theirs`)
    }

    async function run(fn: () => Promise<unknown>, ok: string) {
        try {
            await fn()
            await props.refresh()
            notify(ok)
        } catch (error) {
            notify(String(error).replace(/^Error:\s*/, ''))
        }
    }
</script>

<template>
    <div
        v-if="state.merging || state.rebasing || conflicts.length"
        class="conflict-banner">
        <div class="conflict-banner-header">
            <AlertTriangle :size="15" />
            <strong v-if="state.rebasing">Rebase in progress — resolve conflicts to continue</strong>
            <strong v-else-if="state.merging">Merge conflict — resolve all files then continue</strong>
            <span class="spacer" />
            <template v-if="state.merging && !state.rebasing">
                <button
                    class="btn small"
                    @click="abortMerge()">
                    <X :size="13" /> Abort merge
                </button>
                <button
                    v-if="conflicts.length === 0"
                    class="btn primary small"
                    @click="continueMerge()">
                    <Check :size="13" /> Continue merge
                </button>
            </template>
            <template v-if="state.rebasing">
                <button
                    class="btn small"
                    @click="abortRebase()">
                    <X :size="13" /> Abort rebase
                </button>
                <button
                    v-if="conflicts.length === 0"
                    class="btn primary small"
                    @click="continueRebase()">
                    <Check :size="13" /> Continue rebase
                </button>
            </template>
        </div>

        <div
            v-for="file in conflicts"
            :key="file"
            class="conflict-row">
            <span
                class="conflict-path"
                :title="file"
                >{{ file }}</span
            >
            <div class="conflict-actions">
                <button
                    class="detail-action"
                    title="Keep our version"
                    @click="takeOurs(file)">
                    Ours
                </button>
                <button
                    class="detail-action"
                    title="Keep their version"
                    @click="takeTheirs(file)">
                    Theirs
                </button>
                <button
                    class="detail-action accent"
                    title="I edited the file manually — mark as resolved"
                    @click="markResolved(file)">
                    <ArrowLeftRight :size="12" /> Mark resolved
                </button>
            </div>
        </div>
    </div>
</template>

// src/renderer/src/components/ConflictBanner.tsx
import { AlertTriangle, ArrowLeftRight, Check, X } from 'lucide-react'
import type { RepoState } from '@shared/types'

interface Props {
  conflicts: string[]
  state: RepoState
  refresh: () => Promise<unknown>
  notify: (m: string) => void
}

export default function ConflictBanner({ conflicts, state, refresh, notify }: Props) {
  if (!state.merging && !state.rebasing && conflicts.length === 0) return null

  const run = async (fn: () => Promise<unknown>, ok: string) => {
    try {
      await fn()
      await refresh()
      notify(ok)
    } catch (err) {
      notify(String(err).replace(/^Error:\s*/, ''))
    }
  }

  return (
    <div className="conflict-banner">
      <div className="conflict-banner-header">
        <AlertTriangle size={15} />
        {state.rebasing ? (
          <strong>Rebase in progress — resolve conflicts to continue</strong>
        ) : state.merging ? (
          <strong>Merge conflict — resolve all files then continue</strong>
        ) : null}
        <span className="spacer" />
        {state.merging && !state.rebasing && (
          <>
            <button className="btn small" onClick={() => void run(() => window.api.abortMerge(), 'Merge aborted')}>
              <X size={13} /> Abort merge
            </button>
            {conflicts.length === 0 && (
              <button className="btn primary small" onClick={() => void run(() => window.api.continueMerge(), 'Merge completed')}>
                <Check size={13} /> Continue merge
              </button>
            )}
          </>
        )}
        {state.rebasing && (
          <>
            <button className="btn small" onClick={() => void run(() => window.api.rebaseAbort(), 'Rebase aborted')}>
              <X size={13} /> Abort rebase
            </button>
            {conflicts.length === 0 && (
              <button className="btn primary small" onClick={() => void run(() => window.api.rebaseContinue(), 'Rebase continued')}>
                <Check size={13} /> Continue rebase
              </button>
            )}
          </>
        )}
      </div>

      {conflicts.map((file) => (
        <div className="conflict-row" key={file}>
          <span className="conflict-path" title={file}>{file}</span>
          <div className="conflict-actions">
            <button className="detail-action" title="Keep our version" onClick={() => void run(() => window.api.conflictTakeSide(file, 'ours'), `${file}: kept ours`)}>
              Ours
            </button>
            <button className="detail-action" title="Keep their version" onClick={() => void run(() => window.api.conflictTakeSide(file, 'theirs'), `${file}: kept theirs`)}>
              Theirs
            </button>
            <button className="detail-action accent" title="I edited the file manually — mark as resolved" onClick={() => void run(() => window.api.markResolved([file]), `${file}: resolved`)}>
              <ArrowLeftRight size={12} /> Mark resolved
            </button>
          </div>
        </div>
      ))}
    </div>
  )
}
