// src/renderer/src/components/TabBar.vue
<script setup lang="ts">
    import { Plus, X } from 'lucide-vue-next'

    interface Tab {
        path: string
        name: string
    }

    defineProps<{ tabs: Tab[]; activeIndex: number }>()
    const emit = defineEmits<{ (e: 'select', index: number): void; (e: 'close', index: number): void; (e: 'open-new'): void }>()
</script>

<template>
    <div
        v-if="tabs.length"
        class="tab-bar">
        <div
            v-for="(tab, index) in tabs"
            :key="tab.path"
            class="repo-tab"
            :class="{ active: index === activeIndex }"
            :title="tab.path"
            @click="emit('select', index)">
            <span>{{ tab.name }}</span>
            <button
                class="icon-btn tab-close"
                :title="`Close ${tab.name}`"
                @click.stop="emit('close', index)">
                <X :size="12" />
            </button>
        </div>
        <button
            class="icon-btn tab-new"
            title="Open another repository"
            @click="emit('open-new')">
            <Plus :size="15" />
        </button>
    </div>
</template>

// src/renderer/src/components/TabBar.tsx
import { FolderGit2, Plus, X } from 'lucide-react'

interface Tab {
  path: string
  name: string
}

interface Props {
  tabs: Tab[]
  activeIndex: number
  onSelect: (index: number) => void
  onClose: (index: number) => void
  onOpenNew: () => void
}

export default function TabBar({ tabs, activeIndex, onSelect, onClose, onOpenNew }: Props) {
  if (tabs.length === 0) return null
  return (
    <div className="tab-bar">
      {tabs.map((tab, index) => (
        <div
          key={tab.path}
          className={`repo-tab${index === activeIndex ? ' active' : ''}`}
          title={tab.path}
          onClick={() => onSelect(index)}
        >
          <FolderGit2 size={13} />
          <span>{tab.name}</span>
          <button
            className="icon-btn tab-close"
            title={`Close ${tab.name}`}
            onClick={(event) => {
              event.stopPropagation()
              onClose(index)
            }}
          >
            <X size={12} />
          </button>
        </div>
      ))}
      <button className="icon-btn tab-new" title="Open another repository" onClick={onOpenNew}>
        <Plus size={15} />
      </button>
    </div>
  )
}
